-- Seed data for ingredient categories
-- Category: fresh (order daily), pantry (order when depleted), staple (never order)

-- ============================================
-- KITCHEN STAPLES (Never order - always available)
-- ============================================
INSERT INTO pantry.ingredient_categories (ingredient_pattern, category, default_shelf_life_days, default_servings_per_pack, is_kitchen_staple) VALUES
('salt|namak', 'staple', 365, 100, true),
('black pepper|kali mirch', 'staple', 365, 100, true),
('turmeric|haldi', 'staple', 365, 100, true),
('red chili powder|lal mirch', 'staple', 365, 100, true),
('cumin seeds|jeera', 'staple', 365, 100, true),
('cumin powder|jeera powder', 'staple', 365, 100, true),
('coriander powder|dhaniya powder', 'staple', 365, 100, true),
('mustard seeds|rai|sarson', 'staple', 365, 100, true),
('garam masala', 'staple', 180, 50, true),
('hing|asafoetida', 'staple', 365, 200, true),
('cooking oil|sunflower oil|vegetable oil', 'staple', 180, 30, true),
('mustard oil|sarson ka tel', 'staple', 180, 30, true),
('ghee', 'staple', 180, 30, true),
('sugar|cheeni', 'staple', 365, 100, true),
('wheat flour|atta|gehun', 'staple', 60, 30, true),
('maida|all purpose flour', 'staple', 90, 30, true),
('besan|gram flour', 'staple', 90, 20, true),
('bay leaf|tej patta', 'staple', 365, 100, true),
('cloves|laung', 'staple', 365, 100, true),
('cardamom|elaichi', 'staple', 365, 100, true),
('cinnamon|dalchini', 'staple', 365, 100, true),
('fennel seeds|saunf', 'staple', 365, 100, true),
('fenugreek seeds|methi dana', 'staple', 365, 100, true),
('curry leaves|kadi patta', 'staple', 14, 20, true),
('dried red chili|sabut lal mirch', 'staple', 365, 100, true),
('kasuri methi|dried fenugreek', 'staple', 180, 50, true),
('chaat masala', 'staple', 180, 50, true),
('kitchen king masala', 'staple', 180, 50, true),
('pav bhaji masala', 'staple', 180, 50, true),
('sambhar powder', 'staple', 180, 50, true),
('baking soda', 'staple', 365, 100, true),
('vinegar', 'staple', 365, 50, true),
('soy sauce', 'staple', 180, 30, true);

-- ============================================
-- FRESH ITEMS (Order daily when needed)
-- ============================================
INSERT INTO pantry.ingredient_categories (ingredient_pattern, category, default_shelf_life_days, default_servings_per_pack, is_kitchen_staple) VALUES
('tomato|tamatar', 'fresh', 3, 5, false),
('onion|pyaaz', 'fresh', 7, 5, false),
('potato|aloo', 'fresh', 7, 5, false),
('ginger|adrak', 'fresh', 7, 10, false),
('garlic|lahsun', 'fresh', 7, 10, false),
('green chili|hari mirch', 'fresh', 3, 10, false),
('coriander leaves|dhaniya patti|cilantro', 'fresh', 2, 3, false),
('mint|pudina', 'fresh', 2, 3, false),
('lemon|nimbu', 'fresh', 5, 5, false),
('cucumber|kheera', 'fresh', 3, 3, false),
('carrot|gajar', 'fresh', 5, 5, false),
('capsicum|shimla mirch|bell pepper', 'fresh', 3, 3, false),
('cabbage|patta gobi', 'fresh', 5, 3, false),
('cauliflower|gobi|phool gobi', 'fresh', 3, 2, false),
('spinach|palak', 'fresh', 2, 2, false),
('brinjal|baingan|eggplant', 'fresh', 3, 3, false),
('lady finger|bhindi|okra', 'fresh', 2, 3, false),
('bottle gourd|lauki|ghiya', 'fresh', 3, 3, false),
('bitter gourd|karela', 'fresh', 3, 3, false),
('peas|matar', 'fresh', 2, 3, false),
('french beans|beans', 'fresh', 3, 3, false),
('mushroom', 'fresh', 2, 2, false),
('zucchini', 'fresh', 3, 3, false),
('beetroot|chukandar', 'fresh', 5, 3, false),
('sweet potato|shakarkandi', 'fresh', 7, 3, false),
('radish|mooli', 'fresh', 3, 3, false),
('paneer', 'fresh', 3, 2, false),
('curd|dahi|yogurt', 'fresh', 5, 3, false),
('milk|doodh', 'fresh', 2, 2, false),
('butter', 'fresh', 14, 7, false),
('cream|malai', 'fresh', 3, 2, false),
('cheese|paneer slice', 'fresh', 7, 5, false),
('banana|kela', 'fresh', 3, 3, false),
('apple|seb', 'fresh', 5, 3, false),
('mango|aam', 'fresh', 3, 3, false),
('papaya|papita', 'fresh', 3, 3, false),
('pomegranate|anar', 'fresh', 5, 3, false),
('grapes|angoor', 'fresh', 3, 3, false),
('orange|santra', 'fresh', 5, 3, false),
('watermelon|tarbooj', 'fresh', 3, 2, false),
('tofu', 'fresh', 5, 3, false),
('sprouts|ankurit', 'fresh', 2, 3, false),
('bread', 'fresh', 3, 5, false),
('eggs|anda', 'fresh', 7, 6, false),
('chicken|murgi', 'fresh', 1, 2, false),
('fish|machli', 'fresh', 1, 2, false);

-- ============================================
-- PANTRY ITEMS (Order when depleted)
-- ============================================
INSERT INTO pantry.ingredient_categories (ingredient_pattern, category, default_shelf_life_days, default_servings_per_pack, is_kitchen_staple) VALUES
('toor dal|arhar dal', 'pantry', 90, 15, false),
('moong dal', 'pantry', 90, 15, false),
('masoor dal|red lentil', 'pantry', 90, 15, false),
('chana dal', 'pantry', 90, 15, false),
('urad dal', 'pantry', 90, 15, false),
('rajma|kidney beans', 'pantry', 90, 10, false),
('chole|chickpeas|kabuli chana', 'pantry', 90, 10, false),
('black chana|kala chana', 'pantry', 90, 10, false),
('rice|chawal|basmati', 'pantry', 180, 20, false),
('brown rice', 'pantry', 180, 15, false),
('quinoa', 'pantry', 180, 10, false),
('oats|jayi', 'pantry', 90, 10, false),
('poha|flattened rice', 'pantry', 90, 10, false),
('suji|semolina|rava', 'pantry', 90, 10, false),
('pasta|macaroni', 'pantry', 180, 5, false),
('noodles|maggi', 'pantry', 180, 5, false),
('vermicelli|sevai', 'pantry', 180, 5, false),
('peanuts|moongfali', 'pantry', 90, 10, false),
('cashew|kaju', 'pantry', 90, 10, false),
('almonds|badam', 'pantry', 90, 10, false),
('raisins|kishmish', 'pantry', 90, 10, false),
('coconut powder|nariyal', 'pantry', 90, 10, false),
('jaggery|gur', 'pantry', 180, 10, false),
('honey|shahad', 'pantry', 365, 15, false),
('tomato ketchup|sauce', 'pantry', 180, 20, false),
('peanut butter', 'pantry', 90, 10, false),
('jam', 'pantry', 90, 10, false),
('pickle|achaar', 'pantry', 180, 30, false),
('papad', 'pantry', 180, 10, false),
('coconut milk', 'pantry', 365, 3, false),
('tamarind|imli', 'pantry', 90, 15, false),
('sesame seeds|til', 'pantry', 180, 20, false),
('flax seeds|alsi', 'pantry', 180, 15, false),
('chia seeds', 'pantry', 180, 15, false);

-- Create text search index for pattern matching
CREATE INDEX idx_ingredient_pattern ON pantry.ingredient_categories USING gin(to_tsvector('english', ingredient_pattern));
